#Code for the Deployment of the frontnend Nginx 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-nginx
  labels:
    app: front-nginx
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: front-nginx
  template:
    metadata:
      labels:
        app: front-nginx
    spec: 
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "500Mib"
            cpu: "500m"
          limits:
            memory: "1024Mib"
            cpu: "1000m"
        ports:
        - containerPort: 80
---
#Code for the Deployment of the app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jboss
  labels: 
    app: jboss
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jboss
  template:
    metadata:
      labels:
        app: jboss
    spec:
      containers:
      - name: jboss
        image: jboss:latest
        resources:
          requests:
            memory: "1024Mib"
            cpu: "1000m"
          limits:
            memory: "2048Mib"
            cpu: "2000m"
        ports:
        - containerPort: 8080
---
#Code for the frontend service of the Nginx Deployment
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: front-nginx
  ports:
  - port: 80
    targetPort: 80
    
---
#Code for the Nginx ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: nginx.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port: 
                  number: 80
