#Code for the frontend service of the Nginx Deployment
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: front-nginx
  ports:
  - port: 80
    targetPort: 80
    




---
#Code for the Deployment of the frontnend Nginx
apiVersion: v1/apps
kind: Deployment
metadata:
  name: front-nginx
  labels:
    app: front-nginx
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: front-nginx
  template:
    metadata:
      labels:
        app: front-nginx
    spec: 
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "500Mib"
            cpu: "500m"
          limits:
            memory: "1024Mib"
            cpu: "1000m"
        ports:
        - containerPort: 80
---
#Code for the 