apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: httpd
  replicas: 5
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: volume-httpd-conf
            mountPath: "/usr/local/apache2/conf/httpd.conf"
            subPath: "httpd.conf"
          - name: volume-httpd-index
            mountPath: "/usr/local/apache2/htdocs/index.html"
            subPath: "index.html"
      volumes:
        - name: volume-httpd-conf
          configMap:
            name: httpd-conf
        - name: volume-httpd-index
          configMap:
            name: httpd-index
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpd.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: httpd.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpd-service
                port:
                  number: 80
